[project]
name = "simple-knn"
version = "0.0.1"
requires-python = ">=3.9"
dependencies = ["torch>=2.2.0"]

[build-system]
requires      = ["setuptools>=68", "wheel", "torch>=2.2.0"]
build-backend = "setuptools.build_meta"